package calculator;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;

public class GUI extends javax.swing.JFrame implements ActionListener {

    StringBuilder expression;

    @SuppressWarnings("LeakingThisInConstructor")
    public GUI() {
        initComponents();
        setActionListenerForAllButtons(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnZero = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnSqr = new javax.swing.JButton();
        btnOneDevideX = new javax.swing.JButton();
        btnDevide = new javax.swing.JButton();
        btnBackspace = new javax.swing.JButton();
        btnCloseBrackets = new javax.swing.JButton();
        btnOpenBrackets = new javax.swing.JButton();
        tfScreen = new javax.swing.JTextField();
        lblExpression = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setPreferredSize(new java.awt.Dimension(455, 535));
        setResizable(false);

        btnZero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnZero.setText("0");

        btnDot.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDot.setText(".");

        btnEqual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEqual.setText("=");

        btnCE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCE.setText("CE");

        btnOne.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOne.setText("1");

        btnTwo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTwo.setText("2");

        btnThree.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThree.setText("3");

        btnPlus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPlus.setText("+");

        btnSeven.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSeven.setText("7");

        btnEight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEight.setText("8");

        btnNine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNine.setText("9");

        btnMulti.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMulti.setText("*");

        btnSub.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSub.setText("-");

        btnSix.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSix.setText("6");

        btnFive.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFive.setText("5");

        btnFour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFour.setText("4");

        btnMod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMod.setText("%");

        btnSqrt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSqrt.setText("√");

        btnSqr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSqr.setText("^");

        btnOneDevideX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnOneDevideX.setText("1/x");

        btnDevide.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDevide.setText("÷");

        btnBackspace.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBackspace.setText("←");

        btnCloseBrackets.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCloseBrackets.setText(")");

        btnOpenBrackets.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnOpenBrackets.setText("(");

        tfScreen.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tfScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfScreen.setText("0");
        tfScreen.setToolTipText("");

        lblExpression.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExpression.setText("expression");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExpression)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnZero)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDot)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnTwo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnThree)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnFive)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSix)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEight)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnNine)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnOpenBrackets, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCloseBrackets)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBackspace)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDevide, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnOneDevideX, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSqrt)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSqr)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCE, btnDot, btnEqual, btnZero});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnOne, btnPlus, btnThree, btnTwo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEight, btnFive, btnFour, btnMulti, btnNine, btnSeven, btnSix, btnSub});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBackspace, btnCloseBrackets, btnDevide, btnMod, btnOneDevideX, btnOpenBrackets, btnSqr, btnSqrt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblExpression)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSqr, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOneDevideX, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDevide, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCloseBrackets, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenBrackets, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCE, btnDot, btnEqual, btnZero});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnOne, btnPlus, btnThree, btnTwo});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEight, btnFive, btnFour, btnMulti, btnNine, btnSeven, btnSix, btnSub});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBackspace, btnCloseBrackets, btnDevide, btnMod, btnOneDevideX, btnOpenBrackets, btnSqr, btnSqrt});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
        });

    }

    @Override
    public void actionPerformed(ActionEvent e) {
        this.expression = new StringBuilder(tfScreen.getText());

        if (e.getSource() == btnBackspace) {
            String result = expression.substring(0, expression.length() - 1);
            if (result.equals("")) {
                tfScreen.setText("0");
            } else {
                tfScreen.setText(result);
            }
        } else if (e.getSource() == btnCE) {
            tfScreen.setText("0");
        } else if (e.getSource() == btnOpenBrackets) {
            setCharacter("(");
        } else if (e.getSource() == btnCloseBrackets) {
            setCharacter(")");
        } // number buttons
        else if (e.getSource() == btnZero) {
            if (!expression.equals("0")) {
                tfScreen.setText(expression.append("0").toString());
            }
        } else if (e.getSource() == btnOne) {
            setCharacter("1");
        } else if (e.getSource() == btnTwo) {
            setCharacter("2");
        } else if (e.getSource() == btnThree) {
            setCharacter("3");
        } else if (e.getSource() == btnFour) {
            setCharacter("4");
        } else if (e.getSource() == btnFive) {
            setCharacter("5");
        } else if (e.getSource() == btnSix) {
            setCharacter("6");
        } else if (e.getSource() == btnSeven) {
            setCharacter("7");
        } else if (e.getSource() == btnEight) {
            setCharacter("8");
        } else if (e.getSource() == btnNine) {
            setCharacter("9");
        } // end of number buttons
        // operator buttons
        else if (e.getSource() == btnPlus) {
            setOperator("+");
        } else if (e.getSource() == btnSub) {
            setOperator("-");
        } else if (e.getSource() == btnMulti) {
            setOperator("*");
        } else if (e.getSource() == btnDevide) {
            setOperator("/");
        } else if (e.getSource() == btnMod) {
            setOperator("%");
        } else if (e.getSource() == btnSqr) {
            setOperator("^");
        } // end of operator buttons
        else if (e.getSource() == btnDot) {
            String lastStr = expression.substring(expression.length() - 1);
            if (!lastStr.equals(".")) {
                tfScreen.setText(expression.append(".").toString());
            }
        } else if (e.getSource() == btnOneDevideX) {
            String lastStr = expression.substring(expression.length() - 1);
            if (Character.isDigit(lastStr.charAt(0)) && !lastStr.equals("0")) {
                String result = appendMathOperator(expression, "1/x");
                tfScreen.setText(result);
            } else {
                for (int i = expression.length() - 1; i >= 0; i--) {
                    if (expression.charAt(i) == '(') {
                        expression.insert(i, "1/");
                        break;
                    }
                }
                tfScreen.setText(expression.toString());
            }
        } else if (e.getSource() == btnSqrt) {
            if (expression.toString().equals("0")) {
                expression.replace(0, expression.length(), "√");
                tfScreen.setText(expression.toString());
                return;
            }
            String lastStr = expression.substring(expression.length() - 1);
            switch (lastStr) {
                case "+":
                case "-":
                case "*":
                case "/":
                case "%":
                case "(": {
                    tfScreen.setText(expression.append("√").toString());
                    break;
                }
                case ")": {
                    for (int i = expression.length() - 1; i >= 0; i--) {
                        if (expression.charAt(i) == '(') {
                            expression.insert(i, '√');
                            tfScreen.setText(expression.toString());
                            break;
                        }
                    }
                    break;
                }
                default: { // last character is number
                    String result = appendMathOperator(expression, "√");
                    tfScreen.setText(result);
                }
            }
        }
        // Equal button
        else {
            Validate val = new Validate(expression.toString());
            if (val.isValid()) {
                String exp = tfScreen.getText();
                ProcessExpression process = new ProcessExpression(expression);
                Calculator cal = new Calculator(process.refactor().toString());
                tfScreen.setText(cal.getResult());
                lblExpression.setText(exp);
            } else {
                lblExpression.setText("SYNTAX ERROR");
            }
        }
    }

    private String appendMathOperator(StringBuilder expression, String operator) {
        StringBuilder number = new StringBuilder();
        int index = 0;
        for (int i = expression.length() - 1; i >= 0; i--) {
            if (Character.isDigit(expression.charAt(i))) {
                number.append(expression.charAt(i));
            } else {
                index = i + 1;
                break;
            }
        }
        number.reverse();

        switch (operator) {
            case "√":
                number.insert(0, "√");
                break;
            case "1/x":
                number.insert(0, "1/");
                break;
        }

        String result = expression.substring(0, index);
        return result + number;
    }

    private void setCharacter(String number) {
        if (expression.toString().equals("0")) {
            tfScreen.setText(number);
        } else {
            tfScreen.setText(expression.append(number).toString());
        }
    }

    private void setOperator(String oper) {
        if (!expression.toString().equals("0")) {
            String lastStr = expression.substring(expression.length() - 1);

            if (lastStr.equals("+") || lastStr.equals("-")
                    || lastStr.equals("*") || lastStr.equals("/") || lastStr.equals("%")) {
                expression.setCharAt(expression.length() - 1, oper.charAt(0));
                tfScreen.setText(expression.toString());
            } else {
                tfScreen.setText(expression.append(oper).toString());
            }
        } else {
            tfScreen.setText(expression.append(oper).toString());
        }
    }

    private void setActionListenerForAllButtons(JFrame frame) {
        Component[] components = frame.getContentPane().getComponents();
        for (Component comp : components) {
            if (comp instanceof JButton) {
                ((JButton) comp).addActionListener(this);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCloseBrackets;
    private javax.swing.JButton btnDevide;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnOneDevideX;
    private javax.swing.JButton btnOpenBrackets;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnSqr;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnSub;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JLabel lblExpression;
    private javax.swing.JTextField tfScreen;
    // End of variables declaration//GEN-END:variables

}
